### ISSUE TITLE
Does not work on all FITS files

### ISSUE THREAD

**Issue by jbanfield** [mhardcastle/radioflux#2]
I have used this on a FITS image that I downloaded from the FIRST survey and the program works wonderfully.  I am now attempting to use this on an image I made with ATCA data and the output prints only the following:

```
Filename is myatcaimagel.fits
FG region is image;ellipse(313.96,365.8,102.24,151.2,0)
BG region is image;ellipse(493.96,136.84,90.72,100.8,0)
beam is 49.9999897508 by 14.9999962966 pixels
beam area is 849.81714258 pixels
```

I have looked in the header and it appears to be complete with BMAJ, BMIN, BPA values.  NCP projection.  Not sure why it no longer works.  Thoughts?

**Comment by mhardcastle** [comment]
Hi Julie

Do you mind sending me the image (outside github), and I'll take a
look? It certainly does work with ATCA images but I may have broken
something in some recent changes...

cheers

Martin

**Comment by jbanfield** [comment]
Just sent the image to you.

**Comment by mhardcastle** [comment]
I believe this is fixed in the latest version of the code.
