### ISSUE TITLE
scipy.stats issues

### ISSUE THREAD

**Issue by xinglunju** [mhardcastle/radioflux#8]
I was using radioflux to measure fluxes but noticed that it doesn't work with the latest scipy (v0.19.0 or above): scipy.stats.nanstd and scipy.stats.nanmean do not seem to exit. Instead, there are now scipy.nanstd and scipy.nanmean which do the same work.
(Sorry I just noticed that there is a new version of radioflux which uses numpy to replace scipy commands... please ignore this issue. Thanks!)

**Comment by mhardcastle** [comment]
Indeed, this is fixed, but I ought to make a new release to make sure that people don't get the old incompatible version... I'll try to remember to do that.
